package config.dependencies

import config.Versions

object Dependencies {
    const val kotlin_standard_library = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Versions.kotlinVersion}"
    const val kotlin_reflect = "org.jetbrains.kotlin:kotlin-reflect:${Versions.kotlinVersion}"
    const val ktx = "androidx.core:core-ktx:${Versions.ktxVersion}"
    const val hilt = "com.google.dagger:hilt-android:${Versions.hiltVersion}"
    const val hilt_viewmodel = "androidx.hilt:hilt-lifecycle-viewmodel:1.0.0"
    const val kotlin_coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.coroutinesVersion}"
    const val kotlin_coroutines_android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.coroutinesVersion}"
    const val kotlin_coroutines_play_services = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services:${Versions.coroutines_play_services}"
    const val retrofit_coroutines_adapter = "com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter:${Versions.retrofit2CoroutineVersion}"
    const val navigation_fragment = "androidx.navigation:navigation-fragment-ktx:${Versions.navComponentsVersion}"
    const val navigation_runtime = "androidx.navigation:navigation-runtime:${Versions.navComponentsVersion}"
    const val room_runtime = "androidx.room:room-runtime:${Versions.roomVersion}"
    const val room_ktx = "androidx.room:room-ktx:${Versions.roomVersion}"
    const val play_core = "com.google.android.play:core:${Versions.playCoreVersion}"
    const val leak_canary = "com.squareup.leakcanary:leakcanary-android:${Versions.leakCanaryVersion}"
    const val firebase_firestore = "com.google.firebase:firebase-firestore-ktx:${Versions.firebase_firestoreVersion}"
    const val firebase_auth = "com.google.firebase:firebase-auth:${Versions.firebaseAuthVersion}"
    const val firebase_analytics = "com.google.firebase:firebase-analytics-ktx:${Versions.firebaseAnalyticsVersion}"
    const val firebase_boom = "com.google.firebase:firebase-bom:${Versions.firebaseBoomVersion}"
    const val firebase_crashlytics = "com.google.firebase:firebase-crashlytics:${Versions.firebaseCrashlyticsVersion}"
    const val lifecycle_runtime = "androidx.lifecycle:lifecycle-runtime:${Versions.lifecycleVersion}"
    const val lifecycle_coroutines = "androidx.lifecycle:lifecycle-livedata-ktx:${Versions.lifecycleVersion}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit2Version}"
    const val retrofit_gson = "com.squareup.retrofit2:converter-gson:${Versions.retrofit2Version}"
    const val retrofit_logger = "com.squareup.okhttp3:logging-interceptor:${Versions.retrofitLoggerVersion}"
    const val navigationFragmentKtx = "androidx.navigation:navigation-fragment-ktx:${Versions.navComponentsVersion}"
    const val navigationUiKtx = "androidx.navigation:navigation-ui-ktx:${Versions.navComponentsVersion}"
    const val navigation_config = "androidx.navigation:navigation-ui-ktx:${Versions.navComponentsVersion}"
    const val navigation_dynamic = "androidx.navigation:navigation-dynamic-features-fragment:${Versions.navComponentsVersion}"
    const val recycler_util = "com.github.gurleensethi:LiteUtilities:v${Versions.recyclerUtilVersion}"
    const val timber_log = "com.jakewharton.timber:timber:${Versions.timberVersion}"
    const val paper_prefs = "io.github.pilgr:paperdb:${Versions.paperPrefVersion}"
    const val multidex = "androidx.multidex:multidex:${Versions.multidex_version}"
    const val play_services = "com.google.android.gms:play-services-fido:${Versions.play_services_version}"
    const val expandable_recycler_util =  "com.github.chriselder:expandable-recycler-view:v:${Versions.expandableRecyclerUtilVersion}"
    const val expandable_recycler_util2 =  "com.github.pokercc:ExpandableRecyclerView:0.8.7"
    const val countrypicker = "com.github.joielechong:countrycodepicker:${Versions.countrypicker}"
    const val otpview = "com.github.mukeshsolanki:android-otpview-pinview:${Versions.otpview}"
    const val lottie_animation = "com.airbnb.android:lottie:${Versions.lottieVersion}"
    const val material_dialog = "com.afollestad.material-dialogs:core:${Versions.materialDialogVersion}"
    const val material_dialog_input = "com.afollestad.material-dialogs:input:${Versions.materialDialogVersion}"
    const val frag_nav = "com.ncapdevi:frag-nav:${Versions.fragNavVersion}"
    const val ripple = "com.gauravbhola.ripplepulsebackground:library:${Versions.rippleVersion}"
    const val ccpcountrypicker = "com.hbb20:ccp:${Versions.ccpountrypicker}"
    const val spotsdialog ="com.github.d-max:spots-dialog:1.1@aar"
    const val smileIdentity = "com.smileidentity:smile-id-sdk:${Versions.smileIdentity}"
    const val play_services_location = "com.google.android.gms:play-services-location:${Versions.mapVersion}"
    const val play_service_maps = "com.google.android.gms:play-services-maps:${Versions.mapVersion}"
    const val google_map_places = "com.google.android.gms:play-services-places:${Versions.mapVersion}"
    const val google_map_library = "com.google.android.libraries.places:places:2.0.0"
}